export default {
  id: "bazaarlink",
  priority: 30,
  hasFree: true,
  alias: "bz",
  display: {
    name: "BazaarLink (Free)",
    icon: "shopping_cart",
    color: "#8B5CF6",
    textIcon: "BZ",
    website: "https://bazaarlink.ai",
    notice: {
      text: "Free tier: 3.6M tokens/month. Claude, GPT, Grok, Gemini models.",
    },
  },
  category: "freeTier",
  transport: {
    baseUrl: "https://bazaarlink.ai/api/v1/chat/completions",
    format: "openai",
    authType: "apikey",
    authHeader: "bearer",
  },
  models: [
    { id: "auto:free", name: "Auto Free (Zero Cost)" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "gpt-5.4-nano", name: "GPT-5.4 Nano" },
    { id: "grok-4.3", name: "Grok 4.3" },
    { id: "grok-4.20", name: "Grok 4.20" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "mimo-v2.5-pro", name: "MiMo-V2.5-Pro" },
    { id: "mistral-large-2512", name: "Mistral Large 3" },
    { id: "llama-4-maverick", name: "Llama 4 Maverick" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
  ],
};
