export default {
  id: "bluesminds",
  priority: 30,
  hasFree: true,
  alias: "bm",
  display: {
    name: "Bluesminds (Free)",
    icon: "psychology",
    color: "#3B82F6",
    textIcon: "BS",
    website: "https://bluesminds.com",
    notice: {
      text: "Free tier: 7.2M tokens/month. GPT-4o, Claude, Gemini, DeepSeek.",
      apiKeyUrl: "https://bluesminds.com",
    },
  },
  category: "freeTier",
  transport: {
    baseUrl: "https://api.bluesminds.com/v1/chat/completions",
    format: "openai",
    authType: "apikey",
    authHeader: "bearer",
  },
  models: [
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "gpt-4.1", name: "GPT-4.1" },
    { id: "gpt-4.1-mini", name: "GPT-4.1 Mini" },
    { id: "gpt-4.1-nano", name: "GPT-4.1 Nano" },
    { id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5" },
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5" },
    { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash" },
    { id: "deepseek-reasoner", name: "DeepSeek Reasoner", supportsReasoning: true },
    { id: "deepseek-chat", name: "DeepSeek Chat" },
    { id: "qwen-plus", name: "Qwen Plus" },
    { id: "kimi-k2", name: "Kimi K2" },
    { id: "glm-4.7", name: "GLM 4.7" },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
  ],
};
