export default {
  id: "nvidia",
  priority: 20,
  hasFree: true,
  alias: "nvidia",
  display: {
    name: "NVIDIA NIM",
    icon: "developer_board",
    color: "#76B900",
    textIcon: "NV",
    website: "https://developer.nvidia.com/nim",
    notice: {
      text: "Free access for NVIDIA Developer Program members (prototyping & testing).",
      apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
    },
  },
  category: "freeTier",
  transport: {
    baseUrl: "https://integrate.api.nvidia.com/v1/chat/completions",
    validateUrl: "https://integrate.api.nvidia.com/v1/models",
  },
  models: [
    { id: "meta/llama-3.3-70b-instruct", name: "Llama 3.3 70B Instruct" },
    { id: "meta/llama-3.2-3b-instruct", name: "Llama 3.2 3B Instruct" },
    { id: "meta/llama-3.2-1b-instruct", name: "Llama 3.2 1B Instruct" },
    { id: "google/gemma-2-2b-it", name: "Gemma 2 2B IT" },
    { id: "meta/llama-3.1-70b-instruct", name: "Llama 3.1 70B Instruct" },
    { id: "meta/llama-3.1-8b-instruct", name: "Llama 3.1 8B Instruct" },
    { id: "mistralai/mixtral-8x7b-instruct-v0.1", name: "Mixtral 8x7B Instruct" },
    { id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning", name: "Nemotron 3 Nano Omni 30B" },
    { id: "nvidia/nemotron-3.5-content-safety", name: "Nemotron 3.5 Content Safety" },
    { id: "moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "z-ai/glm-5.1", name: "GLM 5.1" },
    { id: "minimaxai/minimax-m3", name: "Minimax M3" },
    { id: "nvidia/nv-embedqa-e5-v5", name: "NV EmbedQA E5 v5", kind: "embedding" },
    { id: "nvidia/parakeet-ctc-1.1b-asr", name: "Parakeet CTC 1.1B", params: ["language"], kind: "stt" },
    { id: "fastpitch", name: "FastPitch", kind: "tts" },
    { id: "tacotron2", name: "Tacotron2", kind: "tts" },
  ],
  serviceKinds: ["llm","tts","embedding"],
  ttsConfig: {
    baseUrl: "https://integrate.api.nvidia.com/v1/audio/speech",
    authType: "apikey",
    authHeader: "bearer",
    format: "nvidia-tts",
  },
  embeddingConfig: { baseUrl: "https://integrate.api.nvidia.com/v1/embeddings", authType: "apikey", authHeader: "bearer" },
};
