export default {
  id: "ollama-cloud",
  priority: 30,
  hasFree: true,
  alias: "ollamacloud",
  display: {
    name: "Ollama Cloud (Free)",
    icon: "cloud",
    color: "#000000",
    textIcon: "OC",
    website: "https://ollama.com",
    notice: {
      text: "Free tier: Light usage. Generate API key at ollama.com/settings/api-keys",
      apiKeyUrl: "https://ollama.com/settings/api-keys",
    },
  },
  category: "freeTier",
  transport: {
    baseUrl: "https://ollama.com/v1/chat/completions",
    format: "openai",
    authType: "apikey",
    authHeader: "bearer",
  },
  models: [
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro", supportsReasoning: true },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash", supportsReasoning: true },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "minimax-m3", name: "MiniMax M3", contextLength: 1048576 },
    { id: "gemma4:31b", name: "Gemma 4 31B" },
    { id: "nemotron-3-super", name: "NVIDIA Nemotron 3 Super" },
    { id: "qwen3.5:397b", name: "Qwen 3.5 397B" },
  ],
  passthroughModels: true,
};
