export default {
  id: "pollinations",
  priority: 30,
  hasFree: true,
  alias: "pol",
  display: {
    name: "Pollinations (Free)",
    icon: "flower",
    color: "#FF6B9D",
    textIcon: "PL",
    website: "https://pollinations.ai",
    notice: {
      text: "Free keyless models: openai, qwen-coder, mistral, deepseek, grok, perplexity. Premium models need API key at enter.pollinations.ai.",
      apiKeyUrl: "https://enter.pollinations.ai",
    },
  },
  category: "freeTier",
  transport: {
    baseUrl: "https://gen.pollinations.ai/v1/chat/completions",
    format: "openai",
    authType: "apikey",
    authHeader: "bearer",
    noAuth: true,
  },
  models: [
    { id: "openai", name: "OpenAI (Free)" },
    { id: "openai-fast", name: "OpenAI Fast (Free)" },
    { id: "openai-large", name: "OpenAI Large (Free)" },
    { id: "qwen-coder", name: "Qwen Coder (Free)" },
    { id: "mistral", name: "Mistral (Free)" },
    { id: "deepseek", name: "DeepSeek (Free)" },
    { id: "grok", name: "Grok (Free)" },
    { id: "gemini-flash-lite-3.1", name: "Gemini Flash Lite 3.1 (Free)" },
    { id: "perplexity-fast", name: "Perplexity Fast (Free)" },
    { id: "perplexity-reasoning", name: "Perplexity Reasoning (Free)" },
    { id: "kimi", name: "Kimi (Free)" },
    { id: "qwen-vision", name: "Qwen Vision (Free)" },
    { id: "nova-fast", name: "Nova Fast (Free)" },
    { id: "glm", name: "GLM (Free)" },
  ],
};
